"""Optional PostgreSQL integration test. Never connects to Neon."""

import importlib
import os
import uuid

import pytest
from alembic.migration import MigrationContext
from alembic.operations import Operations
from sqlalchemy import create_engine, text
from sqlalchemy.engine import make_url
from sqlalchemy.exc import IntegrityError
from sqlalchemy.pool import NullPool


@pytest.fixture
def isolated_database():
    raw_url = os.getenv("TEST_POSTGRES_URL")
    if not raw_url:
        pytest.skip("Set TEST_POSTGRES_URL to an isolated local PostgreSQL test database")
    url = make_url(raw_url)
    if (url.drivername != "postgresql+psycopg"
            or url.host not in {"localhost", "127.0.0.1", "::1"}
            or not (url.database or "").startswith("test_")):
        pytest.fail("TEST_POSTGRES_URL must target a local PostgreSQL test_ database")

    engine = create_engine(url, poolclass=NullPool)
    try:
        with engine.connect() as connection:
            with connection.begin():
                schema = "ride_req_test_" + uuid.uuid4().hex
                connection.execute(text(f'CREATE SCHEMA "{schema}"'))
                connection.execute(text(f'SET LOCAL search_path TO "{schema}"'))
                connection.execute(text(
                    "CREATE TYPE routestudentstatus AS ENUM ('ACTIVE', 'CANCELLED')"
                ))
                connection.execute(text('CREATE TABLE "user" (id integer PRIMARY KEY)'))
                connection.execute(text(
                    "CREATE TABLE route (id integer PRIMARY KEY, capacity integer NOT NULL)"
                ))
                connection.execute(text("""
                    CREATE TABLE routestudents (
                        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        student_id integer NOT NULL REFERENCES "user"(id),
                        route_id integer NOT NULL REFERENCES route(id),
                        status routestudentstatus NOT NULL
                    )
                """))
                connection.execute(text('INSERT INTO "user" (id) VALUES (1), (2)'))
                connection.execute(text('INSERT INTO route (id, capacity) VALUES (1, 2)'))

                migration = importlib.import_module(
                    "migrations.versions.20261009_0002_ride_requests_seat_integrity"
                )
                migration.op = Operations(MigrationContext.configure(connection))
                migration.upgrade()
                yield connection
                # Rolling back the outer transaction removes the schema and
                # all test rows, types, indexes, and constraints together.
                connection.rollback()
    finally:
        engine.dispose()


def expect_integrity_error(connection, statement, parameters):
    with pytest.raises(IntegrityError), connection.begin_nested():
        connection.execute(text(statement), parameters)


def test_postgres_requests_and_seat_constraints(isolated_database):
    c = isolated_database
    request_insert = (
        "INSERT INTO ride_request (student_id, route_id) "
        "VALUES (:student_id, 1) RETURNING id, status, created_at, version"
    )
    first = c.execute(text(request_insert), {"student_id": 1}).one()
    assert first.status == "PENDING"
    assert first.created_at.tzinfo is not None
    assert first.version == 1
    expect_integrity_error(c, request_insert, {"student_id": 1})
    expect_integrity_error(c, request_insert, {"student_id": 999})

    c.execute(text("UPDATE ride_request SET status = 'DECLINED' WHERE id = :id"),
              {"id": first.id})
    second = c.execute(text(request_insert), {"student_id": 1}).one()
    assert second.status == "PENDING"
    c.execute(text("UPDATE ride_request SET status = 'ACCEPTED' WHERE id = :id"),
              {"id": second.id})
    assert c.execute(text("SELECT status FROM ride_request WHERE id = :id"),
                     {"id": second.id}).scalar_one() == "ACCEPTED"

    enrollment = (
        "INSERT INTO routestudents (student_id, route_id, status) "
        "VALUES (1, 1, :status)"
    )
    c.execute(text(enrollment), {"status": "ACTIVE"})
    expect_integrity_error(c, enrollment, {"status": "ACTIVE"})
    c.execute(text(enrollment), {"status": "CANCELLED"})
    c.execute(text(enrollment), {"status": "CANCELLED"})
    expect_integrity_error(c, "UPDATE route SET capacity = 0 WHERE id = 1", {})
