window.DarbStudentViews = `
    <section class="journey-hero" id="journey">
      <div class="hero-copy"><p class="eyebrow-label" id="dayLabel">YOUR UNIVERSITY JOURNEY</p><h1>Good morning, <span id="studentFirstName">student</span>.</h1><p class="hero-intro">Compare the routes that fit your day, request a seat, and follow every update from one place.</p>
        <div class="route-summary" aria-label="Saved journey"><div><span>From</span><strong id="homeArea">Your area</strong></div><span class="route-arrow" aria-hidden="true">→</span><div><span>To</span><strong id="university">Your university</strong></div><div class="arrival-summary"><span>Arrive by</span><strong id="arrivalTime">—</strong></div></div>
        <div class="hero-actions"><button class="primary-action" id="findRouteButton" type="button">Find matching routes</button><button class="text-action" id="editJourneyButton" type="button">Review journey details</button></div><p class="action-note" id="actionNote" aria-live="polite">Arrival time helps rank routes, but it will not hide other useful matches.</p>
      </div>
      <div class="journey-scene" aria-label="Your saved route from home to university"><div class="scene-map" id="sceneMap" aria-label="Interactive map showing the route from your area to your university"><p>Loading your route map…</p></div><div class="scene-map-shade" aria-hidden="true"></div><div class="scene-heading"><span>Your route</span><strong id="sceneStatus">Ready to search</strong></div><div class="scene-route-details"><div><span class="map-point student-point" id="sceneStudentInitial" aria-hidden="true">S</span><span><small>Starting from</small><strong id="sceneHomeArea">Your area</strong></span></div><span class="map-detail-line" aria-hidden="true"></span><div><span class="map-point campus-point" aria-hidden="true"></span><span><small>Arriving at</small><strong id="sceneUniversity">Your university</strong></span></div></div><div class="scene-time"><span>Target arrival</span><strong id="sceneArrivalTime">—</strong></div></div>
    </section>

    <section id="journeyProgressSection" class="journey-progress-section" aria-labelledby="progressTitle"><div class="section-intro compact"><div><p class="eyebrow-label">CURRENT JOURNEY</p><h2 id="progressTitle">Where your journey stands.</h2></div><p id="progressSummary">Your details are saved. Search when you are ready.</p></div><ol class="journey-progress" id="journeyProgress"><li class="is-complete" data-stage="details"><span>1</span><div><small>DETAILS SAVED</small><strong id="progressHome">Your area</strong></div></li><li class="is-active" data-stage="search"><span>2</span><div><small>SEARCH</small><strong id="progressSearch">Ready to find routes</strong></div></li><li data-stage="request"><span>3</span><div><small>REQUEST</small><strong id="progressRequest">No request yet</strong></div></li><li data-stage="accepted"><span>4</span><div><small>MY ROUTE</small><strong id="progressAccepted">Waiting for driver decision</strong></div></li></ol></section>

    <section class="dashboard-section route-search-section" id="routeSearch" aria-labelledby="routesTitle"><div class="section-intro"><div><p class="eyebrow-label">MATCHING ROUTES</p><h2 id="routesTitle">Choose the route that fits you.</h2></div><p>Compare schedule, driver, seats, and price. Your strongest match appears first, but the choice stays yours.</p></div>
      <div class="search-start" id="searchStart"><div><span class="search-orbit" aria-hidden="true"><i></i><i></i><i></i></span><p class="panel-label">READY WHEN YOU ARE</p><h3>Search with your saved journey.</h3><p>We will use your area, university, and preferred arrival time.</p></div><dl><div><dt>Area</dt><dd id="preferenceArea">—</dd></div><div><dt>University</dt><dd id="preferenceUniversity">—</dd></div><div><dt>Arrival</dt><dd id="preferenceTime">—</dd></div></dl><button class="primary-action" id="panelFindRouteButton" type="button">Search with these details</button></div>
      <div class="search-loading" id="searchingState" hidden><span class="loading-route" aria-hidden="true"><i></i><i></i><i></i></span><p class="panel-label">CHECKING AVAILABLE JOURNEYS</p><h3>Comparing routes around your day…</h3><p>Arrival time affects ranking only. Useful routes will still appear.</p></div>
      <div class="route-results" id="routeResults" hidden><div class="results-toolbar"><div><strong id="matchCount">6 routes match your journey</strong><span id="resultsNote">Sorted by strongest match</span></div><div class="filter-controls"><label>Sort<select id="sortRoutes"><option value="match">Best match</option><option value="departure">Departure time</option><option value="price">Price</option><option value="seats">Available seats</option></select></label><label>Seats<select id="seatFilter"><option value="0">Any</option><option value="2">2+</option><option value="3">3+</option><option value="4">4+</option></select></label></div></div><div class="route-grid" id="routeGrid"></div></div>
      <div class="no-routes" id="noRoutesState" hidden><p class="panel-label">NO SUITABLE ROUTE YET</p><h3>Daro is still looking for your match.</h3><p>Register this journey once and we will keep it visible for future route opportunities.</p><button class="primary-action" id="joinWaitlistButton" type="button">Join waitlist</button></div>
    </section>

    <section class="dashboard-section" id="requests" aria-labelledby="requestsTitle"><div class="section-intro"><div><p class="eyebrow-label">MY REQUESTS</p><h2 id="requestsTitle">Track every seat request.</h2></div><p>Follow each request from pending review to the driver's acceptance or rejection.</p></div><div class="request-list" id="requestList"></div><div class="section-empty" id="requestsEmpty" hidden><h3>No seat requests yet.</h3><p>Search available routes and request the one that works best for you.</p><a class="secondary-action" href="routes.html">Explore routes</a></div></section>

    <section class="dashboard-section waitlist-section" id="waitlist" aria-labelledby="waitlistTitle" hidden><div class="section-intro"><div><p class="eyebrow-label">MY WAITLIST</p><h2 id="waitlistTitle">Your journey stays active.</h2></div><p>We keep looking for a driver and route that match your university day.</p></div><article class="waitlist-card" id="waitlistCard"></article></section>
    <section class="dashboard-section upcoming-section" id="upcomingRide" aria-labelledby="upcomingTitle" hidden><div class="section-intro"><div><p class="eyebrow-label">YOUR UPCOMING RIDE</p><h2 id="upcomingTitle">Everything you need before pickup.</h2></div><p>Your accepted ride, pickup point, and schedule are collected here.</p></div><article class="upcoming-card" id="upcomingCard"></article></section>
  `;
