-- Align admin geography with js/data/iraq-catalogue.js used by student registration.
-- Run once before admin_demo_data.sql. Re-running safely updates matching university governorates.
-- Area names may repeat across governorates, so uniqueness is on name and city together.

ALTER TABLE university ADD COLUMN IF NOT EXISTS governorate VARCHAR;
CREATE INDEX IF NOT EXISTS ix_university_governorate ON university (governorate);

UPDATE university SET "University_name" = 'جامعة بغداد', governorate = 'Baghdad'
WHERE "University_name" = 'University of Baghdad'
  AND NOT EXISTS (SELECT 1 FROM university WHERE "University_name" = 'جامعة بغداد');
UPDATE university SET "University_name" = 'الجامعة المستنصرية', governorate = 'Baghdad'
WHERE "University_name" = 'Al-Mustansiriyah University'
  AND NOT EXISTS (SELECT 1 FROM university WHERE "University_name" = 'الجامعة المستنصرية');
UPDATE area SET "Area_name" = 'المنصور' WHERE "Area_name" = 'Al-Mansour' AND city = 'Baghdad'
  AND NOT EXISTS (SELECT 1 FROM area WHERE "Area_name" = 'المنصور' AND city = 'Baghdad');
UPDATE area SET "Area_name" = 'الكرادة' WHERE "Area_name" = 'Al-Karrada' AND city = 'Baghdad'
  AND NOT EXISTS (SELECT 1 FROM area WHERE "Area_name" = 'الكرادة' AND city = 'Baghdad');
UPDATE area SET "Area_name" = 'الأعظمية' WHERE "Area_name" = 'Adhamiya' AND city = 'Baghdad'
  AND NOT EXISTS (SELECT 1 FROM area WHERE "Area_name" = 'الأعظمية' AND city = 'Baghdad');

DROP INDEX IF EXISTS "ix_area_Area_name";
CREATE INDEX IF NOT EXISTS "ix_area_Area_name" ON area ("Area_name");
CREATE UNIQUE INDEX IF NOT EXISTS uq_area_name_city ON area ("Area_name", city);

INSERT INTO university ("University_name", governorate, status, created_at) VALUES
('جامعة بغداد', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('الجامعة المستنصرية', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('الجامعة التكنولوجية', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة النهرين', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('الجامعة العراقية', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة تكنولوجيا المعلومات والاتصالات', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة الكرخ للعلوم', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة ابن سينا للعلوم الطبية والصيدلانية', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('الجامعة التقنية الوسطى', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('كلية الإمام الكاظم', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('كلية الإمام الأعظم الجامعة', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة البصرة', 'Basra', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة البصرة للنفط والغاز', 'Basra', 'ACTIVE', CURRENT_TIMESTAMP),
('الجامعة التقنية الجنوبية', 'Basra', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة الموصل', 'Nineveh', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة نينوى', 'Nineveh', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة الحمدانية', 'Nineveh', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة تلعفر', 'Nineveh', 'ACTIVE', CURRENT_TIMESTAMP),
('الجامعة التقنية الشمالية', 'Nineveh', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة الأنبار', 'Anbar', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة الفلوجة', 'Anbar', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة بابل', 'Babil', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة القاسم الخضراء', 'Babil', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة كربلاء', 'Karbala', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة الكوفة', 'Najaf', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة جابر بن حيان للعلوم الطبية والصيدلانية', 'Najaf', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة الفرات الأوسط التقنية', 'Najaf', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة ديالى', 'Diyala', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة تكريت', 'Salah al-Din', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة سامراء', 'Salah al-Din', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة كركوك', 'Kirkuk', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة القادسية', 'Qadisiyah', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة واسط', 'Wasit', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة ميسان', 'Maysan', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة ذي قار', 'Dhi Qar', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة سومر', 'Dhi Qar', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة الشطرة', 'Dhi Qar', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة المثنى', 'Muthanna', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة صلاح الدين', 'Erbil', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة هولير الطبية', 'Erbil', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة كوية', 'Erbil', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة سوران', 'Erbil', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة أربيل التقنية', 'Erbil', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة كردستان هولير', 'Erbil', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة السليمانية', 'Sulaymaniyah', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة رابرين', 'Sulaymaniyah', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة كرميان', 'Sulaymaniyah', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة جرمو', 'Sulaymaniyah', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة السليمانية التقنية', 'Sulaymaniyah', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة كرميان التقنية', 'Sulaymaniyah', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة دهوك', 'Duhok', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة زاخو', 'Duhok', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة دهوك التقنية', 'Duhok', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة عقرة للعلوم التطبيقية', 'Duhok', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة حلبجة', 'Halabja', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة التراث', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('كلية المنصور الجامعة', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('كلية الرافدين الجامعة', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة المأمون', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة شط العرب', 'Basra', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة المعارف', 'Anbar', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة الحدباء', 'Nineveh', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة العلوم العراقية', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('كلية اليرموك الجامعة', 'Diyala', 'ACTIVE', CURRENT_TIMESTAMP),
('كلية بغداد للعلوم الطبية', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة اهل البيت', 'Karbala', 'ACTIVE', CURRENT_TIMESTAMP),
('الجامعة الاسلامية', 'Najaf', 'ACTIVE', CURRENT_TIMESTAMP),
('الجامعة الإسلامية — فرع القادسية', 'Qadisiyah', 'ACTIVE', CURRENT_TIMESTAMP),
('الجامعة الإسلامية — فرع بابل', 'Babil', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة دجلة', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('كلية السلام الجامعة', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة الكفيل', 'Najaf', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة مدينة العلم', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة الشيخ الطوسي', 'Najaf', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة الامام جعفر الصادق', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة الإمام جعفر الصادق — فرع ديالى', 'Diyala', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة الإمام جعفر الصادق — فرع كركوك', 'Kirkuk', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة الإمام جعفر الصادق — فرع ذي قار', 'Dhi Qar', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة الإمام جعفر الصادق — فرع النجف', 'Najaf', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة الإمام جعفر الصادق — فرع صلاح الدين', 'Salah al-Din', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة الإمام جعفر الصادق — فرع ميسان', 'Maysan', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة الإمام جعفر الصادق — فرع المثنى', 'Muthanna', 'ACTIVE', CURRENT_TIMESTAMP),
('كلية الرشيد الجامعة', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('كلية العراق الجامعة', 'Basra', 'ACTIVE', CURRENT_TIMESTAMP),
('كلية صدر العراق الجامعة', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة القلم', 'Kirkuk', 'ACTIVE', CURRENT_TIMESTAMP),
('كلية الحسين  الجامعة', 'Karbala', 'ACTIVE', CURRENT_TIMESTAMP),
('كلية الحكمة الجامعة', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة المستقبل', 'Babil', 'ACTIVE', CURRENT_TIMESTAMP),
('كلية الحضارة الجامعة', 'Salah al-Din', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة الحلة', 'Babil', 'ACTIVE', CURRENT_TIMESTAMP),
('كلية اصول العلم الجامعة', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة الاسراء', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة الصفوة', 'Karbala', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة الكتاب', 'Kirkuk', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة الكوت', 'Wasit', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة الفراهيدي', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة المصطفى', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('كلية مزايا الجامعة', 'Dhi Qar', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة النور', 'Nineveh', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة الكنوز', 'Basra', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة الفارابي', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('كلية الطف الجامعة', 'Karbala', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة الزهراوي', 'Karbala', 'ACTIVE', CURRENT_TIMESTAMP),
('كلية النخبة الجامعة', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة النسور', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('كلية الفقه الجامعة', 'Najaf', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة بلاد الرافدين', 'Diyala', 'ACTIVE', CURRENT_TIMESTAMP),
('الجامعة الوطنية للعلوم والتكنولوجيا', 'Dhi Qar', 'ACTIVE', CURRENT_TIMESTAMP),
('كلية الآمال الجامعة', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة الفرقدين الجامعة', 'Basra', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة اوروك', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة الهادي', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة البيان', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة وارث الانبياء', 'Karbala', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة الامين', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة العميد', 'Karbala', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة آشور', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة المنارة', 'Maysan', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة العين العراقية', 'Dhi Qar', 'ACTIVE', CURRENT_TIMESTAMP),
('كلية الشرق الاوسط الجامعة', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('كلية العمارة الجامعة', 'Maysan', 'ACTIVE', CURRENT_TIMESTAMP),
('كلية الادريسي الجامعة', 'Anbar', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة الزهراء  للبنات', 'Karbala', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة كلكامش', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('الجامعة الامريكية', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة المعقل', 'Basra', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة المشرق', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('كلية ابن خلدون', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('كلية الهدى', 'Anbar', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة ساوة', 'Muthanna', 'ACTIVE', CURRENT_TIMESTAMP),
('كلية الامل للعلوم الطبية التخصصية', 'Karbala', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة الشعب', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة السبطين الدولية للعلوم الطبية', 'Karbala', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة الناجي', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة النبراس', 'Salah al-Din', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة قرطبة', 'Najaf', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة سومو', 'Babil', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة بابا كركر', 'Kirkuk', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة الفرقان', 'Nineveh', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة السراج', 'Anbar', 'ACTIVE', CURRENT_TIMESTAMP),
('كلية عشتار الجامعة', 'Babil', 'ACTIVE', CURRENT_TIMESTAMP),
('كلية الشرق للعلوم التقنية التخصصية', 'Basra', 'ACTIVE', CURRENT_TIMESTAMP),
('كلية ملتقى النهرين', 'Basra', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة سهل نينوى', 'Nineveh', 'ACTIVE', CURRENT_TIMESTAMP),
('كلية الوركاء', 'Basra', 'ACTIVE', CURRENT_TIMESTAMP),
('كلية القبس', 'Nineveh', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة نولج', 'Erbil', 'ACTIVE', CURRENT_TIMESTAMP),
('الجامعة اللبنانية الفرنسية', 'Erbil', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة جيهان — أربيل', 'Erbil', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة أربيل الدولية', 'Erbil', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة بيان', 'Erbil', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة تيشك الدولية', 'Erbil', 'ACTIVE', CURRENT_TIMESTAMP),
('الجامعة الكاثوليكية في أربيل', 'Erbil', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة القلعة', 'Erbil', 'ACTIVE', CURRENT_TIMESTAMP),
('الجامعة البريطانية الدولية', 'Erbil', 'ACTIVE', CURRENT_TIMESTAMP),
('الجامعة الأمريكية في العراق — السليمانية', 'Sulaymaniyah', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة التنمية البشرية', 'Sulaymaniyah', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة جيهان — السليمانية', 'Sulaymaniyah', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة كومار للعلوم والتكنولوجيا', 'Sulaymaniyah', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة تيشك — السليمانية', 'Sulaymaniyah', 'ACTIVE', CURRENT_TIMESTAMP),
('كلية كويژة الجامعة', 'Sulaymaniyah', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة قيوان الدولية', 'Sulaymaniyah', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة نوروز', 'Duhok', 'ACTIVE', CURRENT_TIMESTAMP),
('جامعة جيهان — دهوك', 'Duhok', 'ACTIVE', CURRENT_TIMESTAMP),
('الجامعة الأمريكية في كردستان', 'Duhok', 'ACTIVE', CURRENT_TIMESTAMP)
ON CONFLICT ("University_name") DO UPDATE SET governorate = EXCLUDED.governorate;

INSERT INTO area ("Area_name", city, status, created_at) VALUES
('الكرادة', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('المنصور', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('الأعظمية', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('الكاظمية', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('زيونة', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('الغدير', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('بغداد الجديدة', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('مدينة الصدر', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('الشعب', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('البنوك', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('الدورة', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('السيدية', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('البياع', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('الجادرية', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('الحارثية', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('اليرموك', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('العامرية', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('الخضراء', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('الجامعة', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('العدل', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('الزعفرانية', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('البلديات', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('الحسينية', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('التاجي', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('أبو غريب', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('المحمودية', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('المدائن', 'Baghdad', 'ACTIVE', CURRENT_TIMESTAMP),
('العشار', 'Basra', 'ACTIVE', CURRENT_TIMESTAMP),
('المعقل', 'Basra', 'ACTIVE', CURRENT_TIMESTAMP),
('الجزائر', 'Basra', 'ACTIVE', CURRENT_TIMESTAMP),
('البراضعية', 'Basra', 'ACTIVE', CURRENT_TIMESTAMP),
('الجبيلة', 'Basra', 'ACTIVE', CURRENT_TIMESTAMP),
('القبلة', 'Basra', 'ACTIVE', CURRENT_TIMESTAMP),
('الحكيمية', 'Basra', 'ACTIVE', CURRENT_TIMESTAMP),
('الطويسة', 'Basra', 'ACTIVE', CURRENT_TIMESTAMP),
('الحيانية', 'Basra', 'ACTIVE', CURRENT_TIMESTAMP),
('الجمعيات', 'Basra', 'ACTIVE', CURRENT_TIMESTAMP),
('الزبير', 'Basra', 'ACTIVE', CURRENT_TIMESTAMP),
('أبو الخصيب', 'Basra', 'ACTIVE', CURRENT_TIMESTAMP),
('شط العرب', 'Basra', 'ACTIVE', CURRENT_TIMESTAMP),
('القرنة', 'Basra', 'ACTIVE', CURRENT_TIMESTAMP),
('المدينة', 'Basra', 'ACTIVE', CURRENT_TIMESTAMP),
('الهارثة', 'Basra', 'ACTIVE', CURRENT_TIMESTAMP),
('سفوان', 'Basra', 'ACTIVE', CURRENT_TIMESTAMP),
('أم قصر', 'Basra', 'ACTIVE', CURRENT_TIMESTAMP),
('الفاو', 'Basra', 'ACTIVE', CURRENT_TIMESTAMP),
('الموصل', 'Nineveh', 'ACTIVE', CURRENT_TIMESTAMP),
('المجموعة الثقافية', 'Nineveh', 'ACTIVE', CURRENT_TIMESTAMP),
('حي الجامعة', 'Nineveh', 'ACTIVE', CURRENT_TIMESTAMP),
('الزهور', 'Nineveh', 'ACTIVE', CURRENT_TIMESTAMP),
('المثنى', 'Nineveh', 'ACTIVE', CURRENT_TIMESTAMP),
('النور', 'Nineveh', 'ACTIVE', CURRENT_TIMESTAMP),
('الحدباء', 'Nineveh', 'ACTIVE', CURRENT_TIMESTAMP),
('العربي', 'Nineveh', 'ACTIVE', CURRENT_TIMESTAMP),
('المنصور', 'Nineveh', 'ACTIVE', CURRENT_TIMESTAMP),
('الدواسة', 'Nineveh', 'ACTIVE', CURRENT_TIMESTAMP),
('تلعفر', 'Nineveh', 'ACTIVE', CURRENT_TIMESTAMP),
('الحمدانية', 'Nineveh', 'ACTIVE', CURRENT_TIMESTAMP),
('بعشيقة', 'Nineveh', 'ACTIVE', CURRENT_TIMESTAMP),
('برطلة', 'Nineveh', 'ACTIVE', CURRENT_TIMESTAMP),
('سنجار', 'Nineveh', 'ACTIVE', CURRENT_TIMESTAMP),
('تلكيف', 'Nineveh', 'ACTIVE', CURRENT_TIMESTAMP),
('القيارة', 'Nineveh', 'ACTIVE', CURRENT_TIMESTAMP),
('مخمور', 'Nineveh', 'ACTIVE', CURRENT_TIMESTAMP),
('عنكاوا', 'Erbil', 'ACTIVE', CURRENT_TIMESTAMP),
('عينكاوة الجديدة', 'Erbil', 'ACTIVE', CURRENT_TIMESTAMP),
('بختياري', 'Erbil', 'ACTIVE', CURRENT_TIMESTAMP),
('شورش', 'Erbil', 'ACTIVE', CURRENT_TIMESTAMP),
('إسكان', 'Erbil', 'ACTIVE', CURRENT_TIMESTAMP),
('زانياري', 'Erbil', 'ACTIVE', CURRENT_TIMESTAMP),
('نازناز', 'Erbil', 'ACTIVE', CURRENT_TIMESTAMP),
('كسنزان', 'Erbil', 'ACTIVE', CURRENT_TIMESTAMP),
('بحركة', 'Erbil', 'ACTIVE', CURRENT_TIMESTAMP),
('شقلاوة', 'Erbil', 'ACTIVE', CURRENT_TIMESTAMP),
('سوران', 'Erbil', 'ACTIVE', CURRENT_TIMESTAMP),
('كويسنجق', 'Erbil', 'ACTIVE', CURRENT_TIMESTAMP),
('خبات', 'Erbil', 'ACTIVE', CURRENT_TIMESTAMP),
('رواندوز', 'Erbil', 'ACTIVE', CURRENT_TIMESTAMP),
('جومان', 'Erbil', 'ACTIVE', CURRENT_TIMESTAMP),
('ميركسور', 'Erbil', 'ACTIVE', CURRENT_TIMESTAMP),
('بختياري', 'Sulaymaniyah', 'ACTIVE', CURRENT_TIMESTAMP),
('سالم', 'Sulaymaniyah', 'ACTIVE', CURRENT_TIMESTAMP),
('سرجنار', 'Sulaymaniyah', 'ACTIVE', CURRENT_TIMESTAMP),
('رابرين', 'Sulaymaniyah', 'ACTIVE', CURRENT_TIMESTAMP),
('توي ملك', 'Sulaymaniyah', 'ACTIVE', CURRENT_TIMESTAMP),
('كانى كوردە', 'Sulaymaniyah', 'ACTIVE', CURRENT_TIMESTAMP),
('بكرجو', 'Sulaymaniyah', 'ACTIVE', CURRENT_TIMESTAMP),
('شورش', 'Sulaymaniyah', 'ACTIVE', CURRENT_TIMESTAMP),
('رانية', 'Sulaymaniyah', 'ACTIVE', CURRENT_TIMESTAMP),
('دوكان', 'Sulaymaniyah', 'ACTIVE', CURRENT_TIMESTAMP),
('دربندخان', 'Sulaymaniyah', 'ACTIVE', CURRENT_TIMESTAMP),
('كلار', 'Sulaymaniyah', 'ACTIVE', CURRENT_TIMESTAMP),
('كفري', 'Sulaymaniyah', 'ACTIVE', CURRENT_TIMESTAMP),
('جمجمال', 'Sulaymaniyah', 'ACTIVE', CURRENT_TIMESTAMP),
('بنجوين', 'Sulaymaniyah', 'ACTIVE', CURRENT_TIMESTAMP),
('قلعة دزة', 'Sulaymaniyah', 'ACTIVE', CURRENT_TIMESTAMP),
('مركز دهوك', 'Duhok', 'ACTIVE', CURRENT_TIMESTAMP),
('مالطا', 'Duhok', 'ACTIVE', CURRENT_TIMESTAMP),
('ماسيكي', 'Duhok', 'ACTIVE', CURRENT_TIMESTAMP),
('شندوخا', 'Duhok', 'ACTIVE', CURRENT_TIMESTAMP),
('بروشكي', 'Duhok', 'ACTIVE', CURRENT_TIMESTAMP),
('نزاركي', 'Duhok', 'ACTIVE', CURRENT_TIMESTAMP),
('زاخو', 'Duhok', 'ACTIVE', CURRENT_TIMESTAMP),
('سميل', 'Duhok', 'ACTIVE', CURRENT_TIMESTAMP),
('العمادية', 'Duhok', 'ACTIVE', CURRENT_TIMESTAMP),
('عقرة', 'Duhok', 'ACTIVE', CURRENT_TIMESTAMP),
('بردرش', 'Duhok', 'ACTIVE', CURRENT_TIMESTAMP),
('شيخان', 'Duhok', 'ACTIVE', CURRENT_TIMESTAMP),
('مركز حلبجة', 'Halabja', 'ACTIVE', CURRENT_TIMESTAMP),
('خورمال', 'Halabja', 'ACTIVE', CURRENT_TIMESTAMP),
('سيروان', 'Halabja', 'ACTIVE', CURRENT_TIMESTAMP),
('بيارة', 'Halabja', 'ACTIVE', CURRENT_TIMESTAMP),
('طويلة', 'Halabja', 'ACTIVE', CURRENT_TIMESTAMP),
('رحيم آوه', 'Kirkuk', 'ACTIVE', CURRENT_TIMESTAMP),
('شورجة', 'Kirkuk', 'ACTIVE', CURRENT_TIMESTAMP),
('الواسطي', 'Kirkuk', 'ACTIVE', CURRENT_TIMESTAMP),
('القادسية', 'Kirkuk', 'ACTIVE', CURRENT_TIMESTAMP),
('المصلى', 'Kirkuk', 'ACTIVE', CURRENT_TIMESTAMP),
('العروبة', 'Kirkuk', 'ACTIVE', CURRENT_TIMESTAMP),
('دوميز', 'Kirkuk', 'ACTIVE', CURRENT_TIMESTAMP),
('الإسكان', 'Kirkuk', 'ACTIVE', CURRENT_TIMESTAMP),
('تسعين', 'Kirkuk', 'ACTIVE', CURRENT_TIMESTAMP),
('الحويجة', 'Kirkuk', 'ACTIVE', CURRENT_TIMESTAMP),
('داقوق', 'Kirkuk', 'ACTIVE', CURRENT_TIMESTAMP),
('الدبس', 'Kirkuk', 'ACTIVE', CURRENT_TIMESTAMP),
('التون كوبري', 'Kirkuk', 'ACTIVE', CURRENT_TIMESTAMP),
('بعقوبة', 'Diyala', 'ACTIVE', CURRENT_TIMESTAMP),
('بعقوبة الجديدة', 'Diyala', 'ACTIVE', CURRENT_TIMESTAMP),
('التحرير', 'Diyala', 'ACTIVE', CURRENT_TIMESTAMP),
('المفرق', 'Diyala', 'ACTIVE', CURRENT_TIMESTAMP),
('المقدادية', 'Diyala', 'ACTIVE', CURRENT_TIMESTAMP),
('الخالص', 'Diyala', 'ACTIVE', CURRENT_TIMESTAMP),
('خانقين', 'Diyala', 'ACTIVE', CURRENT_TIMESTAMP),
('بلدروز', 'Diyala', 'ACTIVE', CURRENT_TIMESTAMP),
('جلولاء', 'Diyala', 'ACTIVE', CURRENT_TIMESTAMP),
('السعدية', 'Diyala', 'ACTIVE', CURRENT_TIMESTAMP),
('بني سعد', 'Diyala', 'ACTIVE', CURRENT_TIMESTAMP),
('مندلي', 'Diyala', 'ACTIVE', CURRENT_TIMESTAMP),
('قزانية', 'Diyala', 'ACTIVE', CURRENT_TIMESTAMP),
('تكريت', 'Salah al-Din', 'ACTIVE', CURRENT_TIMESTAMP),
('القادسية', 'Salah al-Din', 'ACTIVE', CURRENT_TIMESTAMP),
('العلم', 'Salah al-Din', 'ACTIVE', CURRENT_TIMESTAMP),
('سامراء', 'Salah al-Din', 'ACTIVE', CURRENT_TIMESTAMP),
('بلد', 'Salah al-Din', 'ACTIVE', CURRENT_TIMESTAMP),
('الدجيل', 'Salah al-Din', 'ACTIVE', CURRENT_TIMESTAMP),
('بيجي', 'Salah al-Din', 'ACTIVE', CURRENT_TIMESTAMP),
('الشرقاط', 'Salah al-Din', 'ACTIVE', CURRENT_TIMESTAMP),
('الدور', 'Salah al-Din', 'ACTIVE', CURRENT_TIMESTAMP),
('طوزخورماتو', 'Salah al-Din', 'ACTIVE', CURRENT_TIMESTAMP),
('الإسحاقي', 'Salah al-Din', 'ACTIVE', CURRENT_TIMESTAMP),
('يثرب', 'Salah al-Din', 'ACTIVE', CURRENT_TIMESTAMP),
('الرمادي', 'Anbar', 'ACTIVE', CURRENT_TIMESTAMP),
('التأميم', 'Anbar', 'ACTIVE', CURRENT_TIMESTAMP),
('الملعب', 'Anbar', 'ACTIVE', CURRENT_TIMESTAMP),
('الورار', 'Anbar', 'ACTIVE', CURRENT_TIMESTAMP),
('الفلوجة', 'Anbar', 'ACTIVE', CURRENT_TIMESTAMP),
('الكرمة', 'Anbar', 'ACTIVE', CURRENT_TIMESTAMP),
('الحبانية', 'Anbar', 'ACTIVE', CURRENT_TIMESTAMP),
('الخالدية', 'Anbar', 'ACTIVE', CURRENT_TIMESTAMP),
('هيت', 'Anbar', 'ACTIVE', CURRENT_TIMESTAMP),
('حديثة', 'Anbar', 'ACTIVE', CURRENT_TIMESTAMP),
('عانة', 'Anbar', 'ACTIVE', CURRENT_TIMESTAMP),
('راوة', 'Anbar', 'ACTIVE', CURRENT_TIMESTAMP),
('القائم', 'Anbar', 'ACTIVE', CURRENT_TIMESTAMP),
('الرطبة', 'Anbar', 'ACTIVE', CURRENT_TIMESTAMP),
('البغدادي', 'Anbar', 'ACTIVE', CURRENT_TIMESTAMP),
('الحلة', 'Babil', 'ACTIVE', CURRENT_TIMESTAMP),
('الجمعية', 'Babil', 'ACTIVE', CURRENT_TIMESTAMP),
('الإسكان', 'Babil', 'ACTIVE', CURRENT_TIMESTAMP),
('الكرامة', 'Babil', 'ACTIVE', CURRENT_TIMESTAMP),
('نادر', 'Babil', 'ACTIVE', CURRENT_TIMESTAMP),
('الهاشمية', 'Babil', 'ACTIVE', CURRENT_TIMESTAMP),
('القاسم', 'Babil', 'ACTIVE', CURRENT_TIMESTAMP),
('المحاويل', 'Babil', 'ACTIVE', CURRENT_TIMESTAMP),
('المسيب', 'Babil', 'ACTIVE', CURRENT_TIMESTAMP),
('الإسكندرية', 'Babil', 'ACTIVE', CURRENT_TIMESTAMP),
('سدة الهندية', 'Babil', 'ACTIVE', CURRENT_TIMESTAMP),
('الكفل', 'Babil', 'ACTIVE', CURRENT_TIMESTAMP),
('المدحتية', 'Babil', 'ACTIVE', CURRENT_TIMESTAMP),
('أبو غرق', 'Babil', 'ACTIVE', CURRENT_TIMESTAMP),
('مركز كربلاء', 'Karbala', 'ACTIVE', CURRENT_TIMESTAMP),
('حي الحسين', 'Karbala', 'ACTIVE', CURRENT_TIMESTAMP),
('حي الحر', 'Karbala', 'ACTIVE', CURRENT_TIMESTAMP),
('العباسية', 'Karbala', 'ACTIVE', CURRENT_TIMESTAMP),
('الإسكان', 'Karbala', 'ACTIVE', CURRENT_TIMESTAMP),
('حي المعلمين', 'Karbala', 'ACTIVE', CURRENT_TIMESTAMP),
('الجدول الغربي', 'Karbala', 'ACTIVE', CURRENT_TIMESTAMP),
('الهندية', 'Karbala', 'ACTIVE', CURRENT_TIMESTAMP),
('عين التمر', 'Karbala', 'ACTIVE', CURRENT_TIMESTAMP),
('الحسينية', 'Karbala', 'ACTIVE', CURRENT_TIMESTAMP),
('الخيرات', 'Karbala', 'ACTIVE', CURRENT_TIMESTAMP),
('مركز النجف', 'Najaf', 'ACTIVE', CURRENT_TIMESTAMP),
('حي الأمير', 'Najaf', 'ACTIVE', CURRENT_TIMESTAMP),
('حي الجامعة', 'Najaf', 'ACTIVE', CURRENT_TIMESTAMP),
('الحنانة', 'Najaf', 'ACTIVE', CURRENT_TIMESTAMP),
('الغدير', 'Najaf', 'ACTIVE', CURRENT_TIMESTAMP),
('النداء', 'Najaf', 'ACTIVE', CURRENT_TIMESTAMP),
('المكرمة', 'Najaf', 'ACTIVE', CURRENT_TIMESTAMP),
('الجمعية', 'Najaf', 'ACTIVE', CURRENT_TIMESTAMP),
('الكوفة', 'Najaf', 'ACTIVE', CURRENT_TIMESTAMP),
('المناذرة', 'Najaf', 'ACTIVE', CURRENT_TIMESTAMP),
('المشخاب', 'Najaf', 'ACTIVE', CURRENT_TIMESTAMP),
('الحيرة', 'Najaf', 'ACTIVE', CURRENT_TIMESTAMP),
('العباسية', 'Najaf', 'ACTIVE', CURRENT_TIMESTAMP),
('الديوانية', 'Qadisiyah', 'ACTIVE', CURRENT_TIMESTAMP),
('حي الجامعة', 'Qadisiyah', 'ACTIVE', CURRENT_TIMESTAMP),
('العروبة', 'Qadisiyah', 'ACTIVE', CURRENT_TIMESTAMP),
('الجمهوري', 'Qadisiyah', 'ACTIVE', CURRENT_TIMESTAMP),
('الإسكان', 'Qadisiyah', 'ACTIVE', CURRENT_TIMESTAMP),
('الشامية', 'Qadisiyah', 'ACTIVE', CURRENT_TIMESTAMP),
('عفك', 'Qadisiyah', 'ACTIVE', CURRENT_TIMESTAMP),
('الحمزة', 'Qadisiyah', 'ACTIVE', CURRENT_TIMESTAMP),
('الدغارة', 'Qadisiyah', 'ACTIVE', CURRENT_TIMESTAMP),
('السنية', 'Qadisiyah', 'ACTIVE', CURRENT_TIMESTAMP),
('غماس', 'Qadisiyah', 'ACTIVE', CURRENT_TIMESTAMP),
('الشنافية', 'Qadisiyah', 'ACTIVE', CURRENT_TIMESTAMP),
('البدير', 'Qadisiyah', 'ACTIVE', CURRENT_TIMESTAMP),
('الكوت', 'Wasit', 'ACTIVE', CURRENT_TIMESTAMP),
('الهورة', 'Wasit', 'ACTIVE', CURRENT_TIMESTAMP),
('الداموك', 'Wasit', 'ACTIVE', CURRENT_TIMESTAMP),
('حي الجهاد', 'Wasit', 'ACTIVE', CURRENT_TIMESTAMP),
('حي المعلمين', 'Wasit', 'ACTIVE', CURRENT_TIMESTAMP),
('العزيزية', 'Wasit', 'ACTIVE', CURRENT_TIMESTAMP),
('الحي', 'Wasit', 'ACTIVE', CURRENT_TIMESTAMP),
('الصويرة', 'Wasit', 'ACTIVE', CURRENT_TIMESTAMP),
('النعمانية', 'Wasit', 'ACTIVE', CURRENT_TIMESTAMP),
('بدرة', 'Wasit', 'ACTIVE', CURRENT_TIMESTAMP),
('جصان', 'Wasit', 'ACTIVE', CURRENT_TIMESTAMP),
('الزبيدية', 'Wasit', 'ACTIVE', CURRENT_TIMESTAMP),
('الأحرار', 'Wasit', 'ACTIVE', CURRENT_TIMESTAMP),
('العمارة', 'Maysan', 'ACTIVE', CURRENT_TIMESTAMP),
('حي الحسين', 'Maysan', 'ACTIVE', CURRENT_TIMESTAMP),
('حي المعلمين', 'Maysan', 'ACTIVE', CURRENT_TIMESTAMP),
('المجر الكبير', 'Maysan', 'ACTIVE', CURRENT_TIMESTAMP),
('الكحلاء', 'Maysan', 'ACTIVE', CURRENT_TIMESTAMP),
('علي الغربي', 'Maysan', 'ACTIVE', CURRENT_TIMESTAMP),
('قلعة صالح', 'Maysan', 'ACTIVE', CURRENT_TIMESTAMP),
('الميمونة', 'Maysan', 'ACTIVE', CURRENT_TIMESTAMP),
('السلام', 'Maysan', 'ACTIVE', CURRENT_TIMESTAMP),
('العدل', 'Maysan', 'ACTIVE', CURRENT_TIMESTAMP),
('كميت', 'Maysan', 'ACTIVE', CURRENT_TIMESTAMP),
('علي الشرقي', 'Maysan', 'ACTIVE', CURRENT_TIMESTAMP),
('الناصرية', 'Dhi Qar', 'ACTIVE', CURRENT_TIMESTAMP),
('الشموخ', 'Dhi Qar', 'ACTIVE', CURRENT_TIMESTAMP),
('أور', 'Dhi Qar', 'ACTIVE', CURRENT_TIMESTAMP),
('سومر', 'Dhi Qar', 'ACTIVE', CURRENT_TIMESTAMP),
('الإسكان', 'Dhi Qar', 'ACTIVE', CURRENT_TIMESTAMP),
('الشطرة', 'Dhi Qar', 'ACTIVE', CURRENT_TIMESTAMP),
('الرفاعي', 'Dhi Qar', 'ACTIVE', CURRENT_TIMESTAMP),
('سوق الشيوخ', 'Dhi Qar', 'ACTIVE', CURRENT_TIMESTAMP),
('الجبايش', 'Dhi Qar', 'ACTIVE', CURRENT_TIMESTAMP),
('قلعة سكر', 'Dhi Qar', 'ACTIVE', CURRENT_TIMESTAMP),
('الغراف', 'Dhi Qar', 'ACTIVE', CURRENT_TIMESTAMP),
('الدواية', 'Dhi Qar', 'ACTIVE', CURRENT_TIMESTAMP),
('الفهود', 'Dhi Qar', 'ACTIVE', CURRENT_TIMESTAMP),
('النصر', 'Dhi Qar', 'ACTIVE', CURRENT_TIMESTAMP),
('الإصلاح', 'Dhi Qar', 'ACTIVE', CURRENT_TIMESTAMP),
('السماوة', 'Muthanna', 'ACTIVE', CURRENT_TIMESTAMP),
('الشرقي', 'Muthanna', 'ACTIVE', CURRENT_TIMESTAMP),
('الغربي', 'Muthanna', 'ACTIVE', CURRENT_TIMESTAMP),
('حي الحسين', 'Muthanna', 'ACTIVE', CURRENT_TIMESTAMP),
('حي المعلمين', 'Muthanna', 'ACTIVE', CURRENT_TIMESTAMP),
('الرميثة', 'Muthanna', 'ACTIVE', CURRENT_TIMESTAMP),
('الخضر', 'Muthanna', 'ACTIVE', CURRENT_TIMESTAMP),
('السلمان', 'Muthanna', 'ACTIVE', CURRENT_TIMESTAMP),
('الوركاء', 'Muthanna', 'ACTIVE', CURRENT_TIMESTAMP),
('المجد', 'Muthanna', 'ACTIVE', CURRENT_TIMESTAMP),
('النجمي', 'Muthanna', 'ACTIVE', CURRENT_TIMESTAMP),
('الدراجي', 'Muthanna', 'ACTIVE', CURRENT_TIMESTAMP),
('السوير', 'Muthanna', 'ACTIVE', CURRENT_TIMESTAMP)
ON CONFLICT ("Area_name", city) DO NOTHING;
